// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rlxnvepelwsjzlsjizcz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJseG52ZXBlbHdzanpsc2ppemN6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3NDEwODIsImV4cCI6MjA2NDMxNzA4Mn0.ik3wYvtk0kx-eT5F1ne9rO5t78zDC-M-IMh97nHMOKA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);